version: '3'

services:
    iobroker:
        build: ./iobroker
        container_name: iobroker-eufy-security
        hostname: iobroker-eufy-security
        # This port is only internal, so we can work on this while another instance of ioBroker is running on the host
        expose:
            - 8081
            - 8082
        volumes:
            - ..:/workspace:cached
            - iobrokerdata-eufy-security:/opt/iobroker
        environment:
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US:en
            - LC_ALL=en_US.UTF-8
            - TZ=Europe/Rome
            - SETGID=1000

    # Reverse proxy to load up-to-date admin sources from the repo
    nginx:
        image: nginx:latest
        depends_on:
            - iobroker
        links:
            - iobroker
        container_name: nginx-eufy-security
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ..:/workspace:cached
        ports:
            # Make the ioBroker admin available under http://localhost:8081
            - 8081:80
            # Make the ioBroker vis available under http://localhost:8082
            - 8082:81

volumes:
    iobrokerdata-eufy-security: